const express = require('express')
const bodyParser = require('body-parser')
const userAgent = require('express-useragent')
const user = require('./private/user')
const files = require('./private/files')
const project = require('./private/project')
const task = require('./private/task')
const auth = require('./public/auth')
const checkJwt = require('../middleware/checkJwt')
const error = require('../middleware/errorHandle')

module.exports = (app) => {
  app.use(bodyParser.urlencoded())
  app.use(bodyParser.json())
  app.use(bodyParser.raw())
  app.use(userAgent.express())
  app.use('/public/files', express.static('public'))
  app.use('/api/auth', auth)
  app.use('/api/users', checkJwt, user)
  app.use('/api/files', checkJwt, files)
  app.use('/api/project', checkJwt, project)
  app.use('/api/task', checkJwt, task)
  app.use(error)
}
